name: fortnite
description: A fortnite api manager library in dart.
version: 1.0.2
homepage: https://github.com/vanxh/fortnite-dart
repository: https://github.com/vanxh/fortnite-dart

environment:
    sdk: ">=2.15.1 <3.0.0"

dependencies:
#   path: ^1.8.0

dev_dependencies:
    lints: ^1.0.0
